-- AlterTable
ALTER TABLE `product` ADD COLUMN `discount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `hasFreeShipping` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasWarranty` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `rating` DOUBLE NOT NULL DEFAULT 5.0,
    ADD COLUMN `reviewCount` INTEGER NOT NULL DEFAULT 0;
